/** Generated by web/scripts/sync-module.mjs — do not edit by hand. */
export const MODULE_META = {
  version: "4.22 Final",
  versionCode: 422,
  updatedAt: "2026-05-21",
} as const;

export type ModuleMeta = typeof MODULE_META;

export function formatModuleUpdatedAt(iso: string, lang: "vi" | "en"): string {
  const [y, m, d] = iso.split("-").map((x) => parseInt(x, 10));
  if (!y || !m || !d) return iso;
  if (lang === "vi") {
    return `${String(d).padStart(2, "0")}/${String(m).padStart(2, "0")}/${y}`;
  }
  return new Date(y, m - 1, d).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

export function moduleVersionLine(lang: "vi" | "en"): string {
  const date = formatModuleUpdatedAt(MODULE_META.updatedAt, lang);
  if (lang === "vi") {
    return `Phiên bản ${MODULE_META.version} · Cập nhật ${date}`;
  }
  return `Version ${MODULE_META.version} · Updated ${date}`;
}
