import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..", "..");
const destRoots = {
  /** Vietnamese: repo root + optional module-overrides/vi */
  vi: path.resolve(__dirname, "..", "module-files-vi"),
  /** English: repo root + module-overrides/en */
  en: path.resolve(__dirname, "..", "module-files-en"),
};

const coreFiles = ["module.prop", "service.sh"];
const modulePropPath = path.join(repoRoot, "module.prop");
const moduleMetaOut = path.resolve(__dirname, "..", "lib", "module-meta.ts");
const libSrc = path.join(repoRoot, "lib");
const binSrc = path.join(repoRoot, "bin");
const custSrc = path.join(repoRoot, "customize.sh");

function copyFileIfExists(src, dst) {
  if (!fs.existsSync(src)) return false;
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
  return true;
}

function copyDirFlatSh(srcDir, dstDir) {
  if (!fs.existsSync(srcDir)) return;
  fs.mkdirSync(dstDir, { recursive: true });
  for (const name of fs.readdirSync(srcDir)) {
    if (!name.endsWith(".sh")) continue;
    fs.copyFileSync(path.join(srcDir, name), path.join(dstDir, name));
  }
}

function copyDirFiles(srcDir, dstDir) {
  if (!fs.existsSync(srcDir)) return;
  fs.mkdirSync(dstDir, { recursive: true });
  for (const name of fs.readdirSync(srcDir)) {
    const src = path.join(srcDir, name);
    if (!fs.statSync(src).isFile()) continue;
    fs.copyFileSync(src, path.join(dstDir, name));
  }
}

function parseModuleProp(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  const meta = { version: "0.0", versionCode: 0 };
  for (const line of raw.split(/\r?\n/)) {
    if (line.startsWith("version=")) {
      meta.version = line.slice("version=".length).trim();
    } else if (line.startsWith("versionCode=")) {
      meta.versionCode = parseInt(line.slice("versionCode=".length).trim(), 10) || 0;
    }
  }
  const st = fs.statSync(filePath);
  meta.updatedAt = new Date(st.mtime).toISOString().slice(0, 10);
  return meta;
}

function writeModuleMetaTs(meta) {
  const body = `/** Generated by web/scripts/sync-module.mjs — do not edit by hand. */
export const MODULE_META = {
  version: ${JSON.stringify(meta.version)},
  versionCode: ${meta.versionCode},
  updatedAt: ${JSON.stringify(meta.updatedAt)},
} as const;

export type ModuleMeta = typeof MODULE_META;

export function formatModuleUpdatedAt(iso: string, lang: "vi" | "en"): string {
  const [y, m, d] = iso.split("-").map((x) => parseInt(x, 10));
  if (!y || !m || !d) return iso;
  if (lang === "vi") {
    return \`\${String(d).padStart(2, "0")}/\${String(m).padStart(2, "0")}/\${y}\`;
  }
  return new Date(y, m - 1, d).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

export function moduleVersionLine(lang: "vi" | "en"): string {
  const date = formatModuleUpdatedAt(MODULE_META.updatedAt, lang);
  if (lang === "vi") {
    return \`Phiên bản \${MODULE_META.version} · Cập nhật \${date}\`;
  }
  return \`Version \${MODULE_META.version} · Updated \${date}\`;
}
`;
  fs.mkdirSync(path.dirname(moduleMetaOut), { recursive: true });
  fs.writeFileSync(moduleMetaOut, body, "utf8");
}

function applyOverrides(lang, destRoot) {
  // Optional overrides folder (mirror module root):
  // repoRoot/module-overrides/vi/... or repoRoot/module-overrides/en/...
  const overRoot = path.join(repoRoot, "module-overrides", lang);
  if (!fs.existsSync(overRoot)) return;

  const walk = (relDir) => {
    const absDir = path.join(overRoot, relDir);
    for (const name of fs.readdirSync(absDir)) {
      const rel = path.join(relDir, name);
      const abs = path.join(overRoot, rel);
      const st = fs.statSync(abs);
      if (st.isDirectory()) walk(rel);
      else copyFileIfExists(abs, path.join(destRoot, rel));
    }
  };

  walk("");
}

function stripUpdateJsonFromModuleProp(raw) {
  return raw
    .split(/\r?\n/)
    .filter((line) => !line.startsWith("updateJson="))
    .join("\n")
    .replace(/\n*$/, "\n");
}

function syncOne(destRoot, lang) {
  fs.rmSync(destRoot, { recursive: true, force: true });
  fs.mkdirSync(destRoot, { recursive: true });

  const propRaw = fs.readFileSync(modulePropPath, "utf8");
  fs.writeFileSync(
    path.join(destRoot, "module.prop"),
    stripUpdateJsonFromModuleProp(propRaw),
    "utf8",
  );
  fs.copyFileSync(path.join(repoRoot, "service.sh"), path.join(destRoot, "service.sh"));

  if (!fs.existsSync(libSrc)) {
    console.error("sync-module: missing ../lib from repo root");
    process.exit(1);
  }

  const libDst = path.join(destRoot, "lib");
  copyDirFlatSh(libSrc, libDst);

  const binDst = path.join(destRoot, "bin");
  copyDirFiles(binSrc, binDst);

  copyFileIfExists(custSrc, path.join(destRoot, "customize.sh"));

  if (lang) applyOverrides(lang, destRoot);
}

syncOne(destRoots.vi, "vi");
syncOne(destRoots.en, "en");

if (!fs.existsSync(modulePropPath)) {
  console.error("sync-module: missing module.prop at repo root");
  process.exit(1);
}
const meta = parseModuleProp(modulePropPath);
writeModuleMetaTs(meta);

console.log(
  `sync-module: module ${meta.version} (${meta.updatedAt}) → web/module-files-* + lib/module-meta.ts`,
);
