#!/system/bin/sh
MOD="/data/adb/modules/TelegramControl"
. "$MOD/config.sh"
. "$MOD/lib/common.sh"
. "$MOD/lib/sms.sh"
line="$(content query --uri content://sms/inbox --projection _id:address:date:body --sort 'date DESC' | grep '^Row:' | head -n1)"
echo "ROW_LEN=$(printf '%s' "$line" | wc -c)"
echo "ADDR=$(_sms_parse_address "$line")"
echo "DATE=$(_sms_parse_date_ms "$line")"
echo "BODY=$(_sms_parse_body_from_row "$line" | head -c 120)"
